In [522]:
while len(stack)>0:
    
    now = stack.pop()
    if now == dest:
        return True
    x = now[1]
    y = now[0]
    if x - 1 > -1:
        if maps[y][x-1] == 0:
            stack.append([y,x-1])
            maps[y,x-1] = 2
    if x + 1 < hori:
        if maps[y][x-1]==1:
            stack.append([y,x+1])
            maps[y,x+1] = 2
    if y - 1 > -1:
        if maps[y-1][x] == 1:
            stack.append([y-1,x])
            maps[y-1,x] = 2
    if y + 1 < verti:
        if maps[y+1][x]==1:
            stack.append([y+1,x])
            maps[y+1][x]=2
return False

In [193]:
a[0][0]

0

In [194]:
stack = []

In [195]:
stack.append(a[0][0])

In [196]:
stack

[0]

In [197]:
dest = maps[5,5]
hori = -1
verti = -1

In [198]:
# while len(stack)>0:
for _ in range(2):
          
    now = stack.pop()
    if now == dest:
        
        print(True)
        x = now[0]
        y = now[0]
        print(f'1stack{stack} now{now} x{x} y{y}')   
    if x - 1 > -1:
        if maps[x][y-1] == 0:
            stack.append([y,x-1])
            maps[x,y-1] = 2
            print(f'2stack{stack} now{now} x{x} y{y}') 
    if x + 1 < hori:
        if maps[x][y-1]==1:
            stack.append([y,x+1])
            maps[x,y+1] = 2
            print(f'3stack{stack} now{now} x{x} y{y}') 
    if y - 1 > -1:
        if maps[x-1][y] == 1:
            stack.append([y-1,x])
            maps[-1,y] = 2
            print(f'4stack{stack} now{now} x{x} y{y}') 
    if y + 1 < verti:
        if maps[x+1][y]==1:
            stack.append([y+1,x])
            maps[x+1][y]=2
            print(f'5stack{stack} now{now} x{x} y{y}') 
    print(f'6stack{stack} now{now} x{x} y{y}')       
print(False)

2stack[[2, 0]] now0 x1 y2
6stack[[2, 0]] now0 x1 y2


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

위는 배운 코드를 그냥 그대로 적용해보려고 print한 흔적들이다.

지금은 해결하고 나서 작성중이다. <br>
처음에 배울때는 이해가 가지안아서 내 나름대로 문제를 이해하고 쉽게 만들어 보았다. 하지만<br>
완전탐색에 가깝기 때문에 만족스럽지 안았다.<br>
그래서 배운 코드를 가지고 구현해보기로 한다.<br>

먼저 문제를 봤을때 어딘가 이해가 확실히 들지 않았다.<br>
예를 들어 <font color=red>갈 수 있는 길</font>은 "0" 이고 <font color=blue>갈 수 없는 길</font>은"1"이라고 할때 <br>
두번째 if문의 maps[y][x-1] == 0: 과 그다음 if 문부터 1이였을때 즉, 막혔을때 stack하여라가 <font color=red>오류</font>였다. 
그래서 하나하나 뜯어가면서 다시 작성했다.<br>

In [715]:
#먼저 지도를 만들었다. 수작업이다

In [716]:
import numpy as np

# np.ones_like
# np.ones((2,3,4),dtype=np.int16)
# np.full((2,2),6)
# np.eye(4)
#
#
#

maps = np.arange(1,37).reshape(6,6)
maps

maps[:]=0
maps

maps[0] = 0 
maps[1,0] = 1
maps[1,2] = 1
maps[1,3] = 1 
maps[1,4] = 1
maps[2,2] = 1
maps[2,4] = 1
maps[3,1] = 1
maps[3,2] = 1
maps[4,2] = 1
maps[4,3] = 1 
maps[4,4] = 1
maps[4,5] = 1
maps[5,0] = 1



#미로랑 같아짐
maps

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 0],
       [0, 0, 1, 0, 1, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0]])

# 벽을 설정해준다.
왼쪽벽 : y는 -1이되면 안된다.<br>
위쪽벽 : x 는 -1이되면 안된다.<br>
오른쪽벽: y 는 6 보다 작아야한다.<br>
아래쪽벽: x는 6 보다 작아야한다.<br>

# 이동경로를 설정해준다.
갈 수 있는 길 = 0<br>
갈 수 없는 길 = 1<br>
왔던길 = 2<br>
처음시작 = [0,0]<br>
destination = [5,5] 도착<br>


### 담을 곳을 만들어준다.
Stack = []<br>

### 좌표를 담을 변수를 만들자
x = now[0] <br>
y = now[1] <br>

### -방향 조건문을 만들자 아래,오른,위,좌 순서로! 
### -검증은 벽으로통일하는 조건문이 좋겠다.

In [721]:
# 리셋용 지도
import numpy as np

maps = np.arange(1,37).reshape(6,6)
maps

maps[:]=0
maps

maps[0] = 0 
maps[1,0] = 1
maps[1,2] = 1
maps[1,3] = 1 
maps[1,4] = 1
maps[2,2] = 1
maps[2,4] = 1
maps[3,1] = 1
maps[3,2] = 1
maps[4,2] = 1
maps[4,3] = 1 
maps[4,4] = 1
maps[4,5] = 1
maps[5,0] = 1



#미로랑 같아짐
maps

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 0],
       [0, 0, 1, 0, 1, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0]])

In [718]:
def BFS1(stack):
    dest = [5,5] #도착정답설정
    hori = 6 #수평
    verti =6 #수직
    
    while stack:
        print(f'{stack}')
        now = stack.pop()
        if now == dest:
#             print('도착!!!!!!!!!!!') 
            return True
            break
        x = now[0]
        y = now[1]
        if x - 1 > -1:                #위쪽 벽
            if maps[x-1][y] == 0:
#                 print('위') 
                stack.append([y,x-1])
                maps[x-1,y] = 2
        if x + 1 < hori:              #아래쪽 벽
            if maps[x+1][y]==0:
#                 print('아래')
                stack.append([x+1,y])
                maps[x+1,y] = 2
        if y - 1 > -1:                # 왼쪽 벽
            if maps[x][y-1] == 0:
#                 print('왼')
                stack.append([x,y-1])
                maps[x,y-1] = 2
        if y + 1 < verti:             # 오른쪽 벽
            if maps[x][y+1]==0:
#                 print('오른')
                stack.append([x,y+1])
                maps[x][y+1]=2
        
            
    return False

In [722]:
def BFS2(stack):
    dest = [5,5] #도착정답설정
    hori = 6 #수평
    verti =6 #수직
    
    while stack:
#         print(f'{stack}')
        now = stack.pop()
        if now == dest:
            print('도착!!!!!!!!!!!') 
            return True
            break
        x = now[0]
        y = now[1]
        if x - 1 > -1:                #위쪽 벽
            if maps[x-1][y] == 0:
                print('위') 
                stack.append([y,x-1])
                maps[x-1,y] = 2
        if x + 1 < hori:              #아래쪽 벽
            if maps[x+1][y]==0:
                print('아래')
                stack.append([x+1,y])
                maps[x+1,y] = 2
        if y - 1 > -1:                # 왼쪽 벽
            if maps[x][y-1] == 0:
                print('왼')
                stack.append([x,y-1])
                maps[x,y-1] = 2
        if y + 1 < verti:             # 오른쪽 벽
            if maps[x][y+1]==0:
                print('오른')
                stack.append([x,y+1])
                maps[x][y+1]=2
        
            
    return False

In [719]:
#print(stack)
stack = [[0,0]] #초기스타트
BFS1(stack)

[[0, 0]]
[[0, 1]]
[[1, 1], [0, 0], [0, 2]]
[[1, 1], [0, 0], [0, 3]]
[[1, 1], [0, 0], [0, 4]]
[[1, 1], [0, 0], [0, 5]]
[[1, 1], [0, 0], [1, 5]]
[[1, 1], [0, 0], [2, 5]]
[[1, 1], [0, 0], [3, 5]]
[[1, 1], [0, 0], [3, 4]]
[[1, 1], [0, 0], [3, 3]]
[[1, 1], [0, 0], [3, 2]]
[[1, 1], [0, 0]]
[[1, 1]]
[[2, 1]]
[[2, 0]]
[[3, 0]]
[[4, 0]]
[[4, 1]]
[[5, 1]]
[[5, 2]]
[[5, 3]]
[[5, 4]]
[[5, 5]]


True

In [723]:
#print(위,아래,왼,오른)
stack = [[0,0]]
BFS2(stack)

오른
아래
왼
오른
오른
오른
오른
아래
아래
아래
왼
왼
위
아래
왼
아래
아래
오른
아래
오른
오른
오른
오른
도착!!!!!!!!!!!


True

In [724]:
# 비교하면 되는지도 
now = [5,5]
dest = [5,5]
now == dest

True

In [714]:
#지나간자리는 2로 만든 발자국
maps

array([[2, 2, 2, 2, 2, 2],
       [1, 2, 1, 1, 1, 2],
       [2, 2, 1, 2, 1, 2],
       [2, 1, 1, 2, 2, 2],
       [2, 2, 1, 1, 1, 1],
       [1, 2, 2, 2, 2, 2]])

# 느낀점

처음 시작 할 때까지만해도 막막했다.   
어디서 부터 고쳐야 할 지 어떻게 설정을 다시해야 할 지 도무지 감이 안왔다.
성격상 빠르게 해결하고 싶지만 그렇게되면 멀리 돌아 갈 것 같아서 스스로 다스리고
돌아가도 이해하고 넘어가자 라는 생각으로 하나하나 뜯고 보고 맛보고 즐기고 했다.
그 과정을 모두 보여드리자면 아래와 같다. 어떻게 바인딩되며 어떻게 결과가 나올지까지 하나하나
하다보니 조금씩조금씩 해결이 되어 갔다. 그 과정이 재미가 있어서 시간가는 줄 모르게 집중이되었다.

앞으로도 이러한 문제를 해결 할 수 있는 원동력+1 한 것 같아 뿌듯하다

# 노가다!!!!!!!!!!!!!!!

In [674]:
stack = [[0,0]] #초기 시작 설정

In [675]:
# 여기서부터 엔터
now = stack.pop()
now

[0, 0]

In [676]:
x = now[0]
y = now[1]

In [677]:
y

0

In [678]:
x

0

In [679]:
#위조건에 맞는 if문 복붙해서 결과보기
#마지막 if문에걸리면 담아주고
stack.append([x,y+1])
stack

[[0, 1]]

In [681]:
# 내가왔던길은 2로 바인딩해준다
maps[x,y+1] = 2

In [682]:
#결과보기!

#맵을 보면 시작이 (0,1)인것 처럼 보인다...
maps
# 몇번의 시도끝에 시작은 상관이 없다는 것을 깨달았다.(왼쪽으로 한번 갈뿐..!)

array([[0, 2, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 0],
       [0, 0, 1, 0, 1, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0]])