# 너비우선 탐색(BFS) Breadth first Search

In [5]:
#라이브러리
import numpy as np

배운 BFS 을 나름대로 변형해보기

In [ ]:
# def BFS():    
#     while len(queue)>0:
    for i in range(3):
        count = len(queue)
        for time in range(count):
            now = queue.pop(0)
            if now == dest:
                return answer
            
#좌표로 담을 수 있게 만들자         

            x = now[0]
            y = now[1]
            if x - 1 > -1:                 #위쪽 벽
                if map[x-1][y] == 0:
    
                    data.append([y,x-1])
                    map[x-1,y] = 2
            if x + 1 < hori:              #아래쪽 벽
                if map[x+1][y]==0:
    
                    data.append([x+1,y])
                    map[x+1,y] = 2
            if y - 1 > -1:                # 왼쪽 벽
                if map[x][y-1] == 0:
   
                    data.append([x,y-1])
                    map[x,y-1] = 2
            if y + 1 < verti:             # 오른쪽 벽
                if map[x][y+1]==0:
   
                    data.append([x,y+1])
                    map[x][y+1]=2
                        
#담은 queue를 뽑을 수 있게 해준다.
#             for i in data:
#                 if i[0]==now and visited[i[1]-1]==False:
#                     queue.append(i[1])
#                     visited[i[1]-1]=True
#                 elif i[1]==now and visited[i[0]-1] ==False:
#                     queue.append(i[0])
#                     visited[i[0]-1]=True
#         answer+=1
#     return answer

# 초기 지도초기화 및 설정

In [122]:
map = np.arange(1,26).reshape(5,5)
map

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [123]:
#지도만들기
map=np.zeros_like(map)

map[1:2,:2] = 1
map[1:2,3:5] = 1
map[3:5,1:2] = 1
map[3:5,3:4] = 1
map

array([[0, 0, 0, 0, 0],
       [1, 1, 0, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0]])

In [124]:
queue = [[0,2]] #출발 좌표
dest = [2,4] #도착 좌표
data = []
hori = 5
verti = 5
map[0,2] = 2 #초기 시작설정 

# 수작업 돌려보기

In [149]:
#좌표로 BFS 구현하기
# while len(queue)>0:

for i in range(1):     #1번씩 반복!
    now = queue.pop(0)
    if now == dest:
        print('정답')
        break
  
    x = now[0]
    y = now[1]
    if x - 1 > -1:                 #위쪽 벽
        if map[x-1][y] == 0:
            queue.append([y,x-1])
            map[x-1,y] = 2
    if x + 1 < hori:              #아래쪽 벽
        if map[x+1][y]==0:
            queue.append([x+1,y])
            map[x+1,y] = 2
    if y - 1 > -1:                # 왼쪽 벽
        if map[x][y-1] == 0:
            queue.append([x,y-1])
            map[x,y-1] = 2
    if y + 1 < verti:             # 오른쪽 벽
        if map[x][y+1]==0:
            queue.append([x,y+1])
            map[x][y+1]=2
print(queue)

정답
[[3, 0], [3, 4]]


# {지도 발자국}  11번탐색(잘 탐색 된 것을 알 수 있다.)

In [118]:
#0번째 Search *초기 (0,2) 설정안하면 이렇게된다.
map

array([[0, 2, 0, 2, 0],
       [1, 1, 2, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0]])

In [126]:
#0번째 Search *초기 설정상태
map

array([[0, 2, 2, 2, 0],
       [1, 1, 2, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0]])

In [128]:
#1번째 Search
map

array([[0, 2, 2, 2, 0],
       [1, 1, 2, 1, 1],
       [0, 0, 2, 0, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0]])

In [130]:
#2번째 Search
map

array([[2, 2, 2, 2, 0],
       [1, 1, 2, 1, 1],
       [0, 0, 2, 0, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0]])

In [132]:
#3번째 Search
map

array([[2, 2, 2, 2, 2],
       [1, 1, 2, 1, 1],
       [0, 0, 2, 0, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0]])

In [134]:
#4번째 Search
map

array([[2, 2, 2, 2, 2],
       [1, 1, 2, 1, 1],
       [0, 2, 2, 2, 0],
       [0, 1, 2, 1, 0],
       [0, 1, 0, 1, 0]])

In [136]:
#5번째 Search
map

array([[2, 2, 2, 2, 2],
       [1, 1, 2, 1, 1],
       [0, 2, 2, 2, 0],
       [0, 1, 2, 1, 0],
       [0, 1, 0, 1, 0]])

In [140]:
#6번째 Search
map

array([[2, 2, 2, 2, 2],
       [1, 1, 2, 1, 1],
       [0, 2, 2, 2, 0],
       [0, 1, 2, 1, 0],
       [0, 1, 2, 1, 0]])

In [142]:
#7번째 Search
map

array([[2, 2, 2, 2, 2],
       [1, 1, 2, 1, 1],
       [2, 2, 2, 2, 0],
       [0, 1, 2, 1, 0],
       [0, 1, 2, 1, 0]])

In [144]:
#8번째 Search
map

array([[2, 2, 2, 2, 2],
       [1, 1, 2, 1, 1],
       [2, 2, 2, 2, 2],
       [0, 1, 2, 1, 0],
       [0, 1, 2, 1, 0]])

In [146]:
#9번째 Search
map

array([[2, 2, 2, 2, 2],
       [1, 1, 2, 1, 1],
       [2, 2, 2, 2, 2],
       [0, 1, 2, 1, 0],
       [0, 1, 2, 1, 0]])

In [148]:
#10번째 Search
map

array([[2, 2, 2, 2, 2],
       [1, 1, 2, 1, 1],
       [2, 2, 2, 2, 2],
       [2, 1, 2, 1, 0],
       [0, 1, 2, 1, 0]])

In [150]:
#11번째 Search 
map
#정답을 찾았다.

array([[2, 2, 2, 2, 2],
       [1, 1, 2, 1, 1],
       [2, 2, 2, 2, 2],
       [2, 1, 2, 1, 2],
       [0, 1, 2, 1, 0]])

# 느낀점

DFS배운것을 구현해보니 BFS구현하는 것이 더 수월해졌다.<br>
코드를 뜯어서 먹는다는 것이 이런건가 싶다.<br>
구현 시간도 많이 줄어서 좋다!<br>